### ISSUE TITLE
Support for Telegram "parse_mode" parameter on message

### ISSUE THREAD

**Issue by syrn0n** [samber/slog-telegram#1]
Hi, 

Currently all messages that are sent to Telegram are leaving "parse_mode" empty, which means that the message is a plain text.
I'd like to send markdown messages (specifically supplying names for hyperlinks like in https://copyprogramming.com/howto/how-to-send-url-link-in-the-message-using-telegram-bot-or-show-a-button-to-open-the-url-link)

Can you please add control over this parameter?

**Comment by samber** [comment]
Did you try the following syntax ?

`[name](url)`

**Comment by syrn0n** [comment]
It's not working, I tried it already. You must specify that parse_mode is markdown. I also tried doing it in debugger. Do you prefer me to make a Pull request with a solution?

**Comment by samber** [comment]
Yes please!

**Comment by syrn0n** [comment]
Done, PR created

**Comment by syrn0n** [comment]
https://github.com/samber/slog-telegram/pull/2

**Comment by samber** [comment]
-> v2.2.0

thanks for the contrib ;)
